import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { createClient } from "@/lib/supabase/server";
import StoreProvider from "@/redux/StoreProvider";
import { Initializer } from "@/redux/Initializer";
import { Navbar } from "@/components/navbar/navbar";
import { SubscribeCart } from "@/components/subscribe-cart";
import PageWrapper from "@/components/page-wrapper";
import { MyCart } from "@/components/my-cart";
import { ReactNode } from "react";
import { AlertStock } from "@/components/alert-stock";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {

  const cookieStore = await cookies()
  const supabase = createClient(cookieStore)

  const { data, error } = await supabase
    .from('categories')
    .select(`
                *,
                products (
                *,
                catalog (
                   *
                )
                )
            `);

  if (error) {
    return (<div>Error la consultar los productos</div>)
  }

  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <Initializer initialData={data} />
          <SubscribeCart />
          <Navbar />
          <PageWrapper>
            <div className="flex w-full h-full justify-center">
              {children}
              <MyCart />
              <AlertStock />
            </div>
          </PageWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
