import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { createClient } from "@/lib/supabase/server";
import StoreProvider from "@/redux/StoreProvider";
import { Initializer } from "@/redux/Initializer";
import { Navbar } from "@/components/navbar/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const supabase = createClient(cookieStore)

  const { data, error } = await supabase
    .from('categories')
    .select(`
                id,
                name,
                slug,
                products (
                id,
                category_id,
                name,
                description,
                catalog (
                    id,
                    size,
                    unit,
                    public_price,
                    bulk_stock,
                    stored_stock,
                    min_stock,
                    percentage_discount,
                    available_discount,
                    start_discount,
                    end_discount
                )
                )
            `);

  if (error) {
    return (<div>Error la consultar los productos</div>)
  }

  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <Initializer initialData={data} />
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
